runtime: python
env: flex
entrypoint: gunicorn -b :$PORT upload:app


runtime_config:
  python_version: 3

handlers:
- url: /.*
  script: upload.app
- url: /static
  static_dir: static

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
